//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Battleship.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral.
        /// </summary>
        public static string Admiral {
            get {
                return ResourceManager.GetString("Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser.
        /// </summary>
        public static string Cruiser {
            get {
                return ResourceManager.GetString("Cruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer.
        /// </summary>
        public static string Destroyer {
            get {
                return ResourceManager.GetString("Destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral has been hit.
        /// </summary>
        public static string HitAdmiral {
            get {
                return ResourceManager.GetString("HitAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser has been hit.
        /// </summary>
        public static string HitCruiser {
            get {
                return ResourceManager.GetString("HitCruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer has been hit.
        /// </summary>
        public static string HitDestroyer {
            get {
                return ResourceManager.GetString("HitDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submarine has been hit.
        /// </summary>
        public static string HitSubmarine {
            get {
                return ResourceManager.GetString("HitSubmarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submarine.
        /// </summary>
        public static string Submarine {
            get {
                return ResourceManager.GetString("Submarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral has been sunk.
        /// </summary>
        public static string SunkAdmiral {
            get {
                return ResourceManager.GetString("SunkAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser has been sunk.
        /// </summary>
        public static string SunkCruiser {
            get {
                return ResourceManager.GetString("SunkCruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer has been sunk.
        /// </summary>
        public static string SunkDestroyer {
            get {
                return ResourceManager.GetString("SunkDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submarine has been sunk.
        /// </summary>
        public static string SunkSubmarine {
            get {
                return ResourceManager.GetString("SunkSubmarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won.
        /// </summary>
        public static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
    }
}
